### PR TITLE
Fix for issues/323

### PR DESCRIPTION
**Pull request by tiancaidao**
Remove redandant ! for flutter 3.0

### CODE REVIEW

**Review by SimonH-Zuma — APPROVED** [review]

**Review by bynalab — APPROVED** [review]

**Comment by bynalab** [comment]
Hi @SimonH-Zuma, When would this changes be added to the package?

**Comment by SimonH-Zuma** [comment]
I genuinely have no idea. I don;t have write access to this repo so cannot merge it. I assume only the repo owner does. So it's either a matter of sitting and waiting, or else forking the repo and using your fork.

**Comment by natintosh** [comment]
Hi @SimonH-Zuma, I am the repo owner... would like to have collaborator access to this repo?

**Comment by SimonH-Zuma** [comment]
Hi @natintosh. Thank you for your reply. I would be happy to have collaborator access. You created a great package used by a lot of people (including me) and I'm sure it must be a lot of work managing it. So I'd be happy to help you out when I can.

**Comment by bynalab** [comment]
> Hi @natintosh. Thank you for your reply. I would be happy to have collaborator access. You created a great package used by a lot of people (including me) and I'm sure it must be a lot of work managing it. So I'd be happy to help you out when I can.

@natintosh  I would love to contribute also.

**Comment by bynalab** [comment]
To fixed issue #323

**Comment by iqfareez** [comment]
Hi. Please make this changes available on pub.dev. Cheers.

**Comment by bynalab** [comment]
> Hi. Please make this changes available on pub.dev. Cheers.

Hi @natintosh, How can we go about this?

**Comment by andrii-matviichuk** [comment]
@bynalab @natintosh Can you please publish this fix? We need it so hard in our app (it's used by 30 000+ users and we want to release the update with flutter 3 asap, but we can't do it without that fix)

**Pull request merged**
