### PR TITLE
feat(TextFormField): expose param inputFormatters

### PR DESCRIPTION
**Pull request by hieuptc**
- [x]  Expose parameter `inputFormatters` for handle validation charactor keyboard not allow for special characters and letters

### CODE REVIEW

**Review by edex96 — APPROVED** [review]
LGTM

**Comment by FarhanSyedain** [comment]
LGTM. However don't update the sdk yet,

**Review by FarhanSyedain — CHANGES_REQUESTED** [review]
Leave the sdk version as it was. Only expose the input formatters

**Comment by FarhanSyedain** [comment]
Closing the request for these reasons:
Too many changes in one commit. 
A single commit is contributing to the change of the SDK. Assigning default values to some variables. As well as the main commit.

Please submit a new PR and only change the inputFormatters

Also , assign default inputFormatters too, we don't want the people to go through an extra step. Also, in my opinion input formaters should't be exposed in the first place.

**Pull request closed without merging**
