### PR TITLE
Upgrade to flutter 3.0.0

### PR DESCRIPTION
**Pull request by Sipioteo**
Remove this question mark and upgrade this package

### CODE REVIEW

**Comment by SarukaUsagi** [comment]
Please publish a new release on pub.dev after merging this PR ! :)

**Comment by awasum** [comment]
This fixes a small null safety warning when you run an app using Flutter 3. Please when will this be released?

**Comment by Valansch** [comment]
@natintosh @LucazzP is this lib still maintained?

**Comment by scatboy777** [comment]
Is it possible to accept this PR ?

**Comment by bynalab** [comment]
Hi @Sipioteo, Thanks for your contribution.
This issue has been fixed in #336 which has been merged.

**Pull request closed without merging**
